name: autoshop
services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:latest
    networks:
      - backend

  app:
    container_name: app
    image: autoshop:latest
    ports:
      - 8080:8080
    environment:
      environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Root
      validate SPRING_FLYWAY_ENABLED: "false"
      SERVER_PORT: "8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

